import { type GameRules } from "@minecraft/server";

export const WEREWOLF_GAMERULES = {
    commandBlockOutput: false,
    commandBlocksEnabled: false,
    doDayLightCycle: false,
    doEntityDrops: false,
    doFireTick: false,
    doImmediateRespawn: true,
    doInsomnia: false,
    doLimitedCrafting: false,
    doMobLoot: false,
    doMobSpawning: false,
    doTileDrops: false,
    doWeatherCycle: false,
    drowningDamage: false,
    fallDamage: false,
    fireDamage: false,
    freezeDamage: false,
    functionCommandLimit: 10000,
    keepInventory: true,
    maxCommandChainLength: 65535,
    mobGriefing: false,
    naturalRegeneration: false,
    playersSleepingPercentage: 0,
    projectilesCanBreakBlocks: false,
    pvp: false,
    randomTickSpeed: 0,
    recipesUnlock: false,
    respawnBlocksExplode: true,
    sendCommandFeedback: false,
    showBorderEffect: false,
    showCoordinates: false,
    showDaysPlayed: false,
    showDeathMessages: false,
    showRecipeMessages: false,
    showTags: false,
    spawnRadius: 0,
    tntExplodes: false,
    tntExplosionDropDecay: false,
} satisfies Partial<GameRules>;
