export const T = {
    setup: {
        title: "werewolf-gamemanager.setting.game.title",
        body: "werewolf-gamemanager.setting.game.body",
        roleSettingsButton: "werewolf-gamemanager.setting.role.title",
        gameSettingsButton: "werewolf-gamemanager.setting.custom.title",
        closeButton: "werewolf-gamemanager.ui.close",
    },
    roleComposition: {
        title: "werewolf-gamemanager.setting.roleComposition.title",
        confirm: "werewolf-gamemanager.setting.roleComposition.confirm",
        noneRoles: "werewolf-gamemanager.setting.roleComposition.noneRoles",
        current: "werewolf-gamemanager.setting.roleComposition.current",
        total: "werewolf-gamemanager.setting.roleComposition.total",
        appliedNotice: "werewolf-gamemanager.setting.roleComposition.appliedRoleChangesNotice",
        appliedTotal: "werewolf-gamemanager.setting.roleComposition.appliedRoleChangesNotice.total",
        historyButton: "werewolf-gamemanager.setting.roleComposition.history.button",
        historyTitle: "werewolf-gamemanager.setting.roleComposition.history.title",
        historyEmpty: "werewolf-gamemanager.setting.roleComposition.history.empty",
        historyRestoreButton: "werewolf-gamemanager.setting.roleComposition.history.restore.button",
        historyNextPage: "werewolf-gamemanager.setting.roleComposition.history.nextPage",
        historyPreviousPage: "werewolf-gamemanager.setting.roleComposition.history.previousPage",
        historyChangedBy: "werewolf-gamemanager.setting.roleComposition.history.changedBy",
        historyChangedAt: "werewolf-gamemanager.setting.roleComposition.history.changedAt",
        historyAfter: "werewolf-gamemanager.setting.roleComposition.history.after",
        savedButton: "werewolf-gamemanager.setting.roleComposition.saved.button",
        savedTitle: "werewolf-gamemanager.setting.roleComposition.saved.title",
        savedSaveCurrentButton: "werewolf-gamemanager.setting.roleComposition.saved.saveCurrent.button",
        savedNameTitle: "werewolf-gamemanager.setting.roleComposition.saved.name.title",
        savedNameLabel: "werewolf-gamemanager.setting.roleComposition.saved.name.label",
        savedNamePlaceholder: "werewolf-gamemanager.setting.roleComposition.saved.name.placeholder",
        savedSubmitButton: "werewolf-gamemanager.setting.roleComposition.saved.submit.button",
        savedDuplicateName: "werewolf-gamemanager.setting.roleComposition.saved.duplicateName",
        savedEmptyName: "werewolf-gamemanager.setting.roleComposition.saved.emptyName",
        savedEmpty: "werewolf-gamemanager.setting.roleComposition.saved.empty",
        savedRestoreButton: "werewolf-gamemanager.setting.roleComposition.saved.restore.button",
        savedDeleteButton: "werewolf-gamemanager.setting.roleComposition.saved.delete.button",
        savedDeleteTitle: "werewolf-gamemanager.setting.roleComposition.saved.delete.title",
        savedDeleteDropdown: "werewolf-gamemanager.setting.roleComposition.saved.delete.dropdown",
        savedDeleteSubmitButton: "werewolf-gamemanager.setting.roleComposition.saved.delete.submit.button",
        savedDeleted: "werewolf-gamemanager.setting.roleComposition.saved.deleted",
        savedSaved: "werewolf-gamemanager.setting.roleComposition.saved.saved",
        savedAt: "werewolf-gamemanager.setting.roleComposition.saved.savedAt",
        savedBy: "werewolf-gamemanager.setting.roleComposition.saved.savedBy",
        savedComposition: "werewolf-gamemanager.setting.roleComposition.saved.composition",
        savedNextPage: "werewolf-gamemanager.setting.roleComposition.saved.nextPage",
        savedPreviousPage: "werewolf-gamemanager.setting.roleComposition.saved.previousPage",
    },
    settings: {
        title: "werewolf-gamemanager.setting.custom.title",
        categoryBody: "werewolf-gamemanager.setting.custom.category.body",
        empty: "werewolf-gamemanager.setting.custom.empty",
        saveButton: "werewolf-gamemanager.setting.custom.save",
        saved: "werewolf-gamemanager.setting.custom.saved",
        uncategorized: "werewolf-gamemanager.setting.custom.uncategorized",
    },
    skill: {
        title: "werewolf-gamemanager.skill.form.title",
        selectBody: "werewolf-gamemanager.skill.form.select.body",
        targetBody: "werewolf-gamemanager.skill.form.target.body",
        notStarted: "werewolf-gamemanager.skill.form.notStarted",
        ended: "werewolf-gamemanager.skill.form.ended",
        dead: "werewolf-gamemanager.skill.form.dead",
        empty: "werewolf-gamemanager.skill.form.empty",
        failed: "werewolf-gamemanager.skill.form.failed",
        canceled: "werewolf-gamemanager.skill.form.canceled",
        noTargets: "werewolf-gamemanager.skill.form.noTargets",
    },
    participation: {
        joined: "werewolf-gamemanager.participation.joined",
        spectating: "werewolf-gamemanager.participation.spectating",
    },
    game: {
        startFailed: "werewolf-gamemanager.game.start.failed",
        roleAssigned: "werewolf-gamemanager.game.role.assigned",
        ended: "werewolf-gamemanager.game.ended",
        winnerSuffix: "werewolf-gamemanager.game.winner.suffix",
    },
} as const;
